# Generated by Django 3.2 on 2023-07-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owners',
            name='email',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
