# Generated by Django 3.2 on 2023-07-25 15:11

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_owners_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='hospital_phone',
        ),
        migrations.AlterField(
            model_name='appointments',
            name='doctor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.doctors'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.owners'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='pet_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pets'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='vaccine_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vaccines'),
        ),
        migrations.AlterField(
            model_name='owners',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='pets',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.owners'),
        ),
    ]
