# Generated by Django 3.2 on 2023-07-25 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20230725_1511'),
        ('api', '0005_doctors_hospital_phone'),
    ]

    operations = [
    ]
