# Generated by Django 3.2 on 2024-01-29 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20230725_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owners',
            name='pet_id',
        ),
    ]
